export { default as Header } from './header/Header.vue'
export { default as Footer } from './footer/Footer.vue'
export { default as UserMenu } from './user-menu/UserMenu.vue'
export { default as Breadcrumbs } from './breadcrumbs/Breadcrumbs.vue'
export { default as ContactWidget } from './contact-widget/ContactWidget.vue'
